# Generated by Django 3.2.9 on 2022-03-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='scores',
            new_name='score',
        ),
    ]
